### ISSUE TITLE
(Bug) Skill Proficiency Checkbox Error (Foundry v10.303, D&D 5e 2.2.2)

### ISSUE THREAD

**Issue by TMGilchrist** [eastcw/foundryvtt-compactBeyond5eSheet#10]
## Note: I appreciate that this module is now targeted at Foundry v11, so if this is something fixed in the newer releases, I apologise for wasting your time! 

Issue occurs on **Foundry v10.303**, using **D&D 5e v2.2.2**
Module versions where bug occurs: **2.0.0**, **2.1.0**, **2.1.1**
All other modules disabled apart from the dependency: **Character Actions List dnd5e v6.1.0** (Latest version)
### Bug:

When attempting to check the skill proficiency checkbox on the character sheet, for any of the 18 skills, nothing happens. Opening the console shows the following error:

![Error reads: "Cannot read properties of null (reading QuerySelector)"](https://i.gyazo.com/479b2f80cbeedd0effd4f113323045b6.png)

Inspecting the proficiency checkbox suggests that the issue could be related to the skill name value missing from each corresponding checkbox?

![No name value on checkbox](https://i.gyazo.com/6c3ea7e0d5a0a5bf1d8932ba81e7ebc9.png)

---

**Comment by eastcw** [comment]
Good spot! I should go through the sheet at some point and just test every button to make sure it works, even if we don't use it very often.. This will be fixed in the next release (solved with f150f52)
