### ISSUE TITLE
Changes made to Currency via World Script aren't being reflected in the Inventory

### ISSUE THREAD

**Issue by TouchfuzzyGH** [eastcw/foundryvtt-compactBeyond5eSheet#13]
In a world script, I have the following changes made:

  CONFIG.DND5E.currencies.gp.label = "Funds";
  CONFIG.DND5E.currencies.gp.abbreviation = "¤";
  
The default sheet shows these changes, but when I switch to Compact Beyond, the field remains labeled "GP".

**Comment by eastcw** [comment]
This was a weird issue caused by the fact that the sheet uses short names for the currency (gp) rather than looking up the long names (gold). I have changed the bahaviour and added a setting so that you can choose whether you want your character sheet to show the full name or the abbreviation.
