### ISSUE TITLE
bug - right click on item

### ISSUE THREAD

**Issue by tirzah2** [eastcw/foundryvtt-compactBeyond5eSheet#16]
hi.
in the new version if i right click on an item in any tab, and there aren't a lot of items (like for example only 1 consumable) then the context menu appears inside the item row with a scrollbar.

**Comment by eastcw** [comment]
Hi! Thanks so much for reporting this! It should be better with the next release (fixed in 5c26ec9). Looking at this issue did make me notice larger issues with the right click context menus that I will also be looking at going forward as well (#17).
