### ISSUE TITLE
[Suggestion] Dark Mode and scalable actions and items size on sheet

### ISSUE THREAD

**Issue by SirAron111** [eastcw/foundryvtt-compactBeyond5eSheet#19]
Is it possible to add a dark mode option to the Sheet? I like the Beyond Layout and this module a lot but i simply can't get away from tidy sheet since it has a dark mode option. And maybe a way to scale down the item and actions size, so more can fit onto the screen.
![Unbenanntttt](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/39855956/fe3e464e-8e7d-42d6-bc88-bacf6025d5ea)
![Unbenannnnnnt](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/39855956/1bdb9828-1467-4f11-8438-c9c5020e0f55)
As an example for dark mode color and how the smaller more compact list makes it easier to see multiple things at once on the tidy sheet 5e module (would be nice especially since the header of the beyond sheet takes up a lot of space.)
Or maybe a compatibility with tidy sheet would be awesome. To get the best of both worlds.

**Comment by eastcw** [comment]
Hi! Thanks for the suggestions! 
At the moment the sheet does support dark mode via [this module](https://foundryvtt.com/packages/package/dnd5e-dark-mode) and potentially other similar. I will certainly look at bringing this 'in house' as it were, as it would make dark mode more obvious and easier to use. 
I will also think about an option to make the lists more compact. I really like having that extra information available in the lists, like the weapon damage etc, and I'm not sure about removing it to make the list more compact. Like I say I'll keep considering and maybe do some experimentation but I can't promise anything on that front at the moment.

**Comment by SirAron111** [comment]
Ah, I didn't mean to remove the info. Just getting rid of needles spaces. Like the empty space between the icons, the extra wide space between stuff like.

Greataxe

Weapon

Simply without the needles spacing in between. Would already make it way more compact and have the icons line up more nicely. (having it be the slightly lighter font already clarifies that it's not part of the item's name)

Greataxe
Weapon
