### ISSUE TITLE
[BUG] All of the fields in the Biography section of the sheet (except Alignment) don't allow you to edit them if they're empty.

### ISSUE THREAD

**Issue by TouchfuzzyGH** [eastcw/foundryvtt-compactBeyond5eSheet#22]
**Version**
Foundry Virtual Tabletop: Version 11 Stable, 11.308
Game System: dnd5e, 2.3.1
Active Modules: 1 (Compact Beyond5e Sheet v2.3.2)
Performance Mode: 2

**Expected behavior**
Hovering over the different fields in the Biography tab, such as Personality Traits or Ideals, should reveal an edit button that allows you to input text...

**Describe the bug**
...but it does not.  Except the Alignment field.  Instead, hovering over a section with no text in it reveals nothing.  If I switch to the default 5e character sheet and input text, then switch back, only then does the edit button appear, but if I clear the field, it disappears once more.

**Comment by eastcw** [comment]
Great spot, thanks for pointing this out!
