### ISSUE TITLE
[BUG] Currency abbreviation label not appearing in inventory.

### ISSUE THREAD

**Issue by PantalaimonpanX** [eastcw/foundryvtt-compactBeyond5eSheet#24]
**Describe the bug**
currency-abbreviation seems to be missing it's text for character sheets when more than one sheet is open.

**To Reproduce**
Open two character sheets and the second character sheet will be missing the currency-abbreviation text for the span. This seems to happen for both game masters and players.

My players seem to not be able to see the currency-abbreviation even with one sheet open sometimes, however i am not able to reproduce it consistently. Sometimes it will be there, and other times it will not be there.

**Expected behavior**
currency-abbreviation text should be there.

**Screenshots**
See the right half of the image.
![image](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/15165610/e71a7a49-f853-4c6a-afa3-443c65d1bfc2)

**Version**
![image](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/15165610/4b04cc8c-2179-49d2-9c1d-212af9d3ed0d)
![image](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/15165610/34922847-89aa-4b0b-8ce4-e939b8029be7)

**Comment by eastcw** [comment]
Thanks for bringing this to my atention, I will look into a fix!
