### ISSUE TITLE
[BUG] Doesn't work with Illandril's Character Sheet Lockdown (5e) v4.0.0

### ISSUE THREAD

**Issue by EddieDover** [eastcw/foundryvtt-compactBeyond5eSheet#26]
**Describe the bug**
Doesn't work with Illandril's Character Sheet Lockdown (5e) version 4.0.0
Fields are not locked down, nor is there a tab at the top to control lockdown.

The version listed as working in the main README is 0.7.x+, so there's just a chance that compatibility is woefully out of date.

**Comment by eastcw** [comment]
It seems like the [4.0.0 release of Character Sheet Lockdown deliberately removes support for sheets other than the official 5e sheet.](https://github.com/illandril/FoundryVTT-sheet5e-lockdown/releases/tag/v4.0.0) I don't know why, or if they're planning on adding that back in future releases. In the meantime I'm afraid all I can really do is remove the stated support from the readme; I would advise making an issue on their project if the feature is important to you

**Comment by EddieDover** [comment]
> I'm afraid all I can really do is remove the stated support from the readme;

Expect a PR to implement this basic functionality by Monday. I already have it working, but I want a solid play test with my two groups this weekend before I push the changes to my fork.

**Comment by EddieDover** [comment]
PR is up. It's not comprehensive, but it is a minimum viable product.
