### ISSUE TITLE
[BUG] Skills are listed in no particular order on a translated sheet.

### ISSUE THREAD

**Issue by Padhiver** [eastcw/foundryvtt-compactBeyond5eSheet#28]
**Describe the bug**
If the French translation of the 5e system is used, skills are listed in a non-alphabetical order on the character sheet. Also, the skills acronyms are in English.

**To Reproduce**
If there are any specific steps needed to reproduce the behavior:
1. Activate the French translation of the 5e system.
2. Look at the character sheet.

**Expected behavior**
Skills should be listed in alphabetical order and acronyms in French.

**Screenshots**
![image](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/assets/80126915/08224c42-13e2-4c0d-9cf5-60a18983344e)

**Version**
Foundry 313
DND 2.3.1
French DND translation : https://github.com/adgranger/foundryvtt-dnd5e-lang-fr-fr
French core translation : https://gitlab.com/baktov.sugar/foundryvtt-lang-fr-fr

**Comment by eastcw** [comment]
It seems like the translation module does its own sorting of the skills (which I suppose makes sense) but that because the associated stats come first on each line it's sorting by those instead as you can see. I will fix this in the next release.

**Comment by eastcw** [comment]
This has been fixed with 7e18a31 and release 2.4.1.
